---
- name: Set SELinux to permissive
  hosts: all
  become: true
  pre_tasks:
  tasks:
    - name: Ensure SELinux is permissive
      ansible.posix.selinux:
        policy: targeted
        state: permissive
