---
- name: Alertmanager Monitoring Demo
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Renew Certificate
      condition: payload.labels.alertname == 'TLSCertificateExpiring'
      action:
        run_job_template:
          name: 'Renew Windows Certificates - Demo Prod'
          organization: 'Demo Prod'
