---
- name: Alertmanager Monitoring Demo
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Renew Certificate
      condition: event.payload.commonLabels.alertname == 'TLSCertificateExpiring' and event.payload.status == 'Firing'
      action:
        run_job_template:
          name: 'Renew Windows Certificates - SpaceShip'
          organization: 'SpaceShip'
