---
- name: Alertmanager Monitoring Demo
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Output Events
      condition:
        all:
          - event.payload.status == 'firing'
          - event.payload.labels.alertname == 'TLSCertificateExpiring'
      action:
        run_job_template:
          name: Renew the Windows Server TLS Certs
          organization: Demo Prod
