---
- name: AWS CloudTrail Monitoring Demo
  hosts: localhost
  sources:
    - name: Listen for Cloudtrail Events
      ansible.eda.aws_cloudtrail:
        region: 'eu-west-1'
        delay_seconds: 2
  rules:
    - name: Output Stop and Start Events
      condition:
        any:
          - event.CloudTrailEvent.eventName == 'StopInstances'
      action:
        print_event:
