---
- name: Remediate SELinux from Alertmanager via Kafka (normalized)
  hosts: all
  execution_strategy: parallel

  sources:
    - name: Listen for alerts on kafka topic
      ansible.eda.kafka:
        host: ec2-52-16-111-5.eu-west-1.compute.amazonaws.com
        port: 9094
        topic: summit-connect
        group_id: eda-selinux
      filters:
        - ansible.eda.json_filter:
        - ansible.eda.normalize_keys:

  rules:
    - name: Remediate selinux issue
      condition: event.body.status == "firing" and event.body.common_labels.alertname == "selinux not enforcing"
      action:
        run_job_template:
          name: Remediate SELinux - Spaceship
          organization: SpaceShip
          job_args:
            limit: "{{ event.body.common_annotations.hostname }}"