---
- name: Check nginx app health and run diagnostics if unavailable
  hosts: all
  execution_strategy: parallel
  sources:
    - name: Listen for alerts onkafka topic
      ansible.eda.kafka:
        host: ec2-13-53-45-113.eu-north-1.compute.amazonaws.com
        port: 9092
        topic: alertmanager-alerts
        group_id: eda-selinux
      filters:
        - ansible.eda.json_filter:
        - ansible.eda.normalize_keys:
  rules: