---
- name: Remediate SELinux from Alertmanager via Kafka (no filters)
  hosts: all
  execution_strategy: parallel

  sources:
    - name: Listen for alerts on kafka topic
      ansible.eda.kafka:
        host: ec2-52-16-111-5.eu-west-1.compute.amazonaws.com
        port: 9094
        topic: summit-connect
        group_id: eda-selinux

  rules:
    - name: Remediate selinux issue
      condition: event.body.commonLabels.alertname == "selinux not enforcing"
      action:
        run_job_template:
          name: Remediate SELinux - Spaceship
          organization: SpaceShip
          job_args:
            # falls back to empty string if hostname missing
            limit: "{{ event.body.commonAnnotations.hostname | default('') }}"
