---
- name: Enable ICMP (allow ping) on RHEL
  hosts: all
  become: true
  gather_facts: false

  vars:
    # Set a zone if you don't use the default zone
    fw_zone: null   # e.g. "public"

  tasks:
    - name: Ensure firewalld is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Ensure firewalld is enabled and running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Unblock inbound ICMP echo requests (permanent + immediate)
      ansible.posix.firewalld:
        icmp_block: echo-request
        state: disabled
        immediate: true
        permanent: true
        zone: "{{ fw_zone | default(omit) }}"

    # This query returns RC=0 when "yes" and RC=1 when "no".
    # Treat both as success and just report the value.
    - name: Verify ICMP echo-request is NOT blocked
      ansible.builtin.command:
        cmd: firewall-cmd --query-icmp-block=echo-request {{ '--zone ' ~ fw_zone if fw_zone else '' }}
      register: icmp_blocked_check
      changed_when: false
      failed_when: false

    - name: Show firewall check result
      ansible.builtin.debug:
        msg: "echo-request blocked? {{ icmp_blocked_check.stdout }} (rc={{ icmp_blocked_check.rc }})"

    - name: Notifiy the dashboard we're complete
      ansible.windows.win_uri:
        method: POST
        url: https://bridge.spaceship.rham.dev/api/controller/ui/home
        headers:
          Authorization: "{{ bearer_token }}"
        body:
          scenario: solar_storm_resolved
        status_code:
          - 204
      tags: ui
