---
- name: Startup the startship engine vm
  hosts: localhost
  gather_facts: false
  become: false
  connection: local

  vars:
    instance_ids:
      - i-022cc9c3860815785

  tasks:
    - name: Startup the AWS instances
      amazon.aws.ec2_instance:
        state: running
        instance_ids: "{{ instance_ids }}"
...
