---
- name: Remediate SELinux mode
  hosts: all
  become: true
  pre_tasks:
  - name: Assert that we only have one host in the play # noqa: run-once[task]
    ansible.builtin.assert:
      that:
        - ansible_play_hosts | length <= 1
      fail_msg: 'Should only be one host in the play.'
    run_once: true
  tasks:
    - name: Ensure SELinux is enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

    - name: Notifiy the dashboard we're complete
      ansible.builtin.uri:
        method: POST
        url: https://bridge.spaceship.rham.dev/api/controller/ui/home
        body_format: json
        headers:
          Authorization: "{{ bearer_token }}"
        body:
          scenario: shields_down_resolved
        status_code:
          - 204
      tags: ui
      delegate_to: localhost
      connection: local
